import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";

import localFont from 'next/font/local'
import { LenisProvider } from "@/components/providers/LenisProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const myFont = localFont({
  src: './fonts/font.woff', // Path to your file
  variable: '--font-custom',           // Optional: CSS variable name
  display: 'swap',
})
const futura = localFont({
  src: './fonts/Futura-Bold.woff2', // Path to your file
  variable: '--font-futura',           // Optional: CSS variable name
  display: 'swap',
})
const social = localFont({
  src: './fonts/ABCSocialMono-Regular.woff2', // Path to your file
  variable: '--font-social',           // Optional: CSS variable name
  display: 'swap',
})
const helvitica = localFont({
  src: './fonts/HelveticaNowText-Regular.woff2', // Path to your file
  variable: '--font-helvitica',           // Optional: CSS variable name
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${helvitica.variable} ${social.variable} ${outfit.variable} ${futura.variable} ${myFont.variable} ${geistMono.variable} antialiased`}
      >

        <LenisProvider>
          {children}
        </LenisProvider>



      </body>
    </html>
  );
}
